name: Ruby Formula Version Bump

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Run script
        run: |
          ruby scripts/bump.rb

      - name: Commit changes
        run: |
          git config user.name "Anderson Freitas"
          git config user.email "freitas@disroot.org"
          # git add Formula/*
          git commit -am "Bump version"
          git push origin HEAD:main -f
